name: dart_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
 dart_jsonwebtoken: ^2.4.2
 mysql1: ^0.20.0
 password_dart: ^2.0.1
 shelf: ^1.4.0
 shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
